import pandas as pd
import matplotlib.pyplot as plt
import os

def plot_battery_voltage_over_time(log_file_path):
    if not os.path.exists(log_file_path):
        print(f"[GROUND STATION ERROR] Telemetry not found at: {log_file_path}")
        print("Make sure you run the command from the project root directory.")
        return

    print(f"[GROUND STATION] Loading telemetry from {log_file_path}...")
    data = pd.read_csv(log_file_path)

    time = data['Time_ms']
    voltage = data['Voltage_V']
    vel_z = data['Vel_Z']

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

    ax1.plot(time, voltage, label='Voltage (V)', color='blue', linewidth=2)
    ax1.axhline(3.5, color='red', linestyle='--', label='Safe Mode Threshold (3.5V)')

    ax1.set_ylabel('Battery Voltage (V)')
    ax1.set_title('OBC Telemetry Panel: Power and GNC')
    ax1.grid(True)
    ax1.legend()

    ax2.plot(time, vel_z, label='Angular Velocity (rad/s)', color='green', linewidth=2)
    ax2.set_xlabel('Time (ms)')
    ax2.set_ylabel('Angular Velocity (rad/s)')
    ax2.grid(True)
    ax2.legend()

    plt.tight_layout()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, '..', 'reports', 'telemetry_panel.png')
    plt.savefig(output_path, dpi=300)
    print(f"[GROUND STATION] Telemetry panel saved to {output_path}")


if __name__ == "__main__":
    log_file_path = 'logs/flight_data.csv'  # Path to the log file generated by the flight software
    plot_battery_voltage_over_time(log_file_path)